import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function Home() {
  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center py-12">
        <h1 className="text-4xl md:text-6xl font-bold text-brand-dark mb-6">
          Welcome to <span className="text-brand-mustard">Cheflyte</span>
        </h1>
        <p className="text-xl text-brand-sage mb-8 max-w-2xl mx-auto">
          AI-powered chef booking platform that connects you with local cooks for personalized meal experiences at home, in pods, or for delivery.
        </p>
        <div className="flex gap-4 justify-center">
          <Link href="/auth/signup">
            <Button size="lg" className="px-8">
              Get Started
            </Button>
          </Link>
          <Link href="/auth/signin">
            <Button variant="outline" size="lg" className="px-8">
              Sign In
            </Button>
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="p-6">
          <h3 className="text-xl font-semibold text-brand-dark mb-3">
            🤖 AI Meal Planning
          </h3>
          <p className="text-brand-sage">
            Get personalized meal plans generated by AI based on your dietary preferences, allergies, and household size.
          </p>
        </Card>

        <Card className="p-6">
          <h3 className="text-xl font-semibold text-brand-dark mb-3">
            👨‍🍳 Local Cooks
          </h3>
          <p className="text-brand-sage">
            Connect with verified local cooks who specialize in your favorite cuisines and dietary requirements.
          </p>
        </Card>

        <Card className="p-6">
          <h3 className="text-xl font-semibold text-brand-dark mb-3">
            🏠 Flexible Service
          </h3>
          <p className="text-brand-sage">
            Choose from home cooking, pod meals, or delivery options that fit your lifestyle and schedule.
          </p>
        </Card>
      </section>

      {/* How It Works Section */}
      <section className="bg-brand-sage/10 rounded-lg p-8">
        <h2 className="text-3xl font-bold text-brand-dark text-center mb-8">
          How It Works
        </h2>
        <div className="grid md:grid-cols-3 gap-8 text-center">
          <div>
            <div className="w-12 h-12 bg-brand-mustard rounded-full flex items-center justify-center text-white font-bold text-xl mx-auto mb-4">
              1
            </div>
            <h3 className="font-semibold text-brand-dark mb-2">Plan Your Meals</h3>
            <p className="text-brand-sage">
              Tell our AI about your preferences and get personalized meal recommendations.
            </p>
          </div>
          <div>
            <div className="w-12 h-12 bg-brand-mustard rounded-full flex items-center justify-center text-white font-bold text-xl mx-auto mb-4">
              2
            </div>
            <h3 className="font-semibold text-brand-dark mb-2">Find Your Cook</h3>
            <p className="text-brand-sage">
              Browse and book local cooks who match your cuisine preferences and schedule.
            </p>
          </div>
          <div>
            <div className="w-12 h-12 bg-brand-mustard rounded-full flex items-center justify-center text-white font-bold text-xl mx-auto mb-4">
              3
            </div>
            <h3 className="font-semibold text-brand-dark mb-2">Enjoy Your Meal</h3>
            <p className="text-brand-sage">
              Relax while your cook prepares a delicious, personalized meal experience.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="text-center py-12 border-t border-brand-sage/20">
        <h2 className="text-2xl font-bold text-brand-dark mb-4">
          Ready to Transform Your Dining Experience?
        </h2>
        <p className="text-brand-sage mb-6">
          Join thousands of food lovers who have discovered the joy of personalized cooking.
        </p>
        <div className="flex gap-4 justify-center">
          <Link href="/auth/signup?role=user">
            <Button size="lg" className="px-8">
              I&apos;m a Food Lover
            </Button>
          </Link>
          <Link href="/auth/signup?role=cook">
            <Button variant="outline" size="lg" className="px-8">
              I&apos;m a Cook
            </Button>
          </Link>
        </div>
      </section>
    </div>
  );
}
